export const mainContainer = "w-full h-full md:h-[35.5rem] flex flex-col justify-between items-center md:px-5 md:mx-0 md:px-24 md:pb-8 md:pt-12"
export const innerForm = "w-fit rounded-lg md:rounded-none md:w-full flex flex-col justify-between items-center bg-white md:bg-transparent p-5 md:p-0 mx-4 md:mx-0 mb-32 md:mb-0"
export const nextBtn = "bg-marine-blue text-white px-6 py-3 text-sm rounded-lg transition-all hover:bg-dark-blue"
export const titleContainer = "flex flex-col w-full items-start justify-around md:gap-3"
export const title = "text-marine-blue font-bold text-2xl md:text-3xl"
export const subtitle = "text-cool-gray"
export const goBackBtn = "py-3 text-cool-gray"
export const navigationContainer = "w-full flex items-center justify-between bg-white md:bg-transparent p-4 md:p-0 fixed bottom-0 md:static"